name: Auto Update M3U (Filtered)

on:
  workflow_dispatch:        # ম্যানুয়ালি চালানো যাবে
  schedule:
    - cron: "0 */6 * * *"   # প্রতি ৬ ঘণ্টায় স্বয়ংক্রিয়ভাবে চালাবে

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install requests

    - name: Run filter script to generate M3U
      run: python filter_m3u.py

    - name: Commit and push filtered M3U
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "Auto Bot"
        git config --global user.email "auto@bot.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add bd-in-pk-sports.m3u
        git commit -m "🔁 Auto-update filtered M3U" || echo "No changes to commit"
        git push origin HEAD:main
