name: Auto Update M3U

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to generate M3U
        run: python filter_m3u.py

      - name: Commit and push
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "auto@example.com"
          git add bd-in-pk-sports.m3u
          git diff --quiet || git commit -m "🔁 Auto-update M3U"
          git push
